//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libe_Escriptori.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lessons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lessons()
        {
            this.attendance = new HashSet<attendance>();
            this.profesors = new HashSet<profesors>();
        }
    
        public int id { get; set; }
        public System.TimeSpan starting_hour { get; set; }
        public System.TimeSpan ending_hour { get; set; }
        public string weekday { get; set; }
        public int schedule_id { get; set; }
        public int module_id { get; set; }
        public int classroom_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendance> attendance { get; set; }
        public virtual classrooms classrooms { get; set; }
        public virtual modules modules { get; set; }
        public virtual schedules schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<profesors> profesors { get; set; }
    }
}
